### PR TITLE
Local spatial resolution (Inner Tracker sensors): Extension of the model to tilted Inner Tracker layouts

### PR DESCRIPTION
**Pull request by ghugo83**
Parametrization model used so far (by Ernesto) is valid for untilted layouts. It is mentioned in [1] and [2].
A study has been carried out by Riccardo del Burgo to obtain a parametrization for tilted Inner Tracker layouts.
alpha and beta angles used in the studies and the code are defined in Figure 7 from [3]. 

In this PR:
- Corrected omission introduced in HitNew and TrackNew classes. 
The statistics on local spatial resolution are displayed in the modules table on the geometry tab on the website.
They are collected each time a track hits a sensor.
They were not appearing anymore.

- Incorporated parametrized model from Riccardo.
Simulation parameters appear in the cfg files.

Results:
They are the following, for untilted Inner Tracker layouts:

- Inner Tracker with pixel aspect ratio 25x100 everywhere:
Ernesto's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/July/OT613_200_IT404/layoutpixel.html
Riccardo's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/September/OT613_200_IT404/layoutpixel.html

- Inner Tracker with pixel aspect ratio 50x50 everywhere:
Ernesto's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/July/OT613_200_IT405/layoutpixel.html
Riccardo's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/September/OT613_200_IT405/layoutpixel.html

Resolution in the FPIX is matching quite well. 
Though there is still a discrepancy observed in the local Y resolution in the Barrel, notably for ~ |cotan(beta)| > 2.0, which needs to be understood.

[1] Parametrization of the spatial resolution of the reconstructed hits in the Inner Pixel for HL-LHC studies, E. Migliore and M. Musich, 2015/09/18
[2] Summary of available parametrizations, E. Migliore, Torino, 2016/06/13
[3] Commissioning and Performance of the CMS Pixel Tracker with Cosmic Ray Muons, The CMS Collaboration, 2010/02/02

NB: Do not merge yet! The diff with Ernesto's parametrization is puzzling and might need adjustments of the parametrization itself.

### CODE REVIEW

**Comment by alkemyst** [comment]
There is still one significant difference between the two parametrisations, and that is under investigation.

The difference lies in the local y resolution of barrel modules for shallow incidence angles.
Here are the two parametrisations with Ernesto's (previous) y local resolution in green and Riccardo's (new) parametrisation in blue.

**Comment by ghugo83** [comment]
Please see PR description for more details.

Final results are as follows:
Untilted Inner Tracker layouts:

- Inner Tracker with pixel aspect ratio 25x100 everywhere:
* Ernesto's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/July/OT613_200_IT404/layoutpixel.html
* Riccardo's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT404/layoutpixel.html 

- Inner Tracker with pixel aspect ratio 50x50 everywhere:
* Ernesto's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/July/OT613_200_IT405/layoutpixel.html
* Riccardo's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT405/layoutpixel.html 


Tilted Inner Tracker layout:
IT503: 50x50 in 1x1 and 1x2 modules, 25x100 in 2x2 modules. 
* Riccardo's parametrization: http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT503/layoutpixel.html 

Please see details at:
https://indico.cern.ch/event/681868/

**Comment by ghugo83** [comment]
NB: Further developments coming in separate PR 
(distribution of hit angles in local and global frame of reference 
+ possibility to tune shape of luminous region 
+ hits on inactive materials from non-0 interaction point).

**Comment by ghugo83** [comment]
Diff of that PR on TDR layout:
Before: http://cms-tklayout.web.cern.ch/cms-tklayout/layouts/repository-git-dev_gabie/OT613_200_IT4025/index.html
After: http://ghugo.web.cern.ch/ghugo/layouts/test/OT613_200_IT4025/info.html

**Comment by alkemyst** [comment]
The slight difference in the expected tracking resolution goes in the same direction as the improvement in the single-hit resolution, so that looks good to me.

**Pull request merged**
