### PR TITLE
Outer Tracker: leave space for BTL and IT insertion.

### PR DESCRIPTION
**Pull request by ghugo83**
http://ghugo.web.cern.ch/ghugo/layouts/test/OT616_200_IT404/layout.html

### CODE REVIEW

**Comment by alkemyst** [comment]
The ditance between ring middle positions 9 → 11 used to be 82.864 in version 6.1.5 and it is 75.814 in version 6.1.6

**Comment by alkemyst** [comment]
The distance between rmax(9) and rmin(11) used to be 35.602 in version 6.1.5

**Comment by ghugo83** [comment]
Thanks Stefano! 
Looks better now :)

**Comment by ghugo83** [comment]
Thanks Stefano!
Looks better now :)
rSafetyMargin forces the distance between Rings 9 and 11.

**Comment by alkemyst** [comment]
Thanks Gabrielle for fixing this. The closest approach is now shown here (I think it's the closest)
closest

**Comment by alkemyst** [comment]
With one millimeter gap this looks feasible now

**Comment by ghugo83** [comment]
Ok let's leave it as it is for now, and see Nick's feedback :)

**Pull request merged**
