### PR TITLE
CMake CleanUp

### PR DESCRIPTION
**Pull request by vvolkl**
Update of #486

### CODE REVIEW

**Comment by ghugo83** [comment]
@vvolkl Thanks a lot!
Please not the const return value in the comparator in Materialway.hh is not strictly needed for successful compilation in C++17 (only the comparator itself needs to be const). 

Am testing this PR now ;)

**Comment by ghugo83** [comment]
Hmm it does not seem to find boost properly :(
Did you test it? Could you test & update?

**Comment by vvolkl** [comment]
Hi @ghugo83 
ah, right, I was talking about changing the `setupCMake_slc6.sh` but then forgot to push it. Since you anyway prefer not sourcing the whole view I updated it in a different way using the `CMAKE_PREFIX_PATH`. I had to also use a newer cmake to use the `CMAKE_CXX_STANDARD` variable. There are some cmake warnings about boost, but it should be ok nonetheless! Could you give it another try?

**Comment by vvolkl** [comment]
Oh, and it seems it's true that the change in the comparator is not needed (anymore? at one point I ran into a compilation error and had to do that to fix it, so there might be some issue with a different compiler). so I removed it.

**Comment by ghugo83** [comment]
Thanks a lot @vvolkl !
- The cmake warnings about boost are due to version of cmake which is still slightly too old.
Loading /cvmfs/sft.cern.ch/lcg/contrib/CMake/3.13.4 instead of 3.8.1 fixes it (otherwise, cmake version is older than boost one).
This also fixes a warning at run time.

- What about compiler flags? 
-std=c++17 -Wall -Werror -fmax-errors=2 -g 
are presently in Makefile, would be nice to have the same flags here.
I do not think -Wall is there by default for example.
(actually would be nice to have more flags but that's a full other story :))

Once these 2 points are fixed I ll merge ur PR :)
Thanks a lot :)

**Comment by vvolkl** [comment]
Good catch, the newer cmake indeed gets rid of the boost warnings. The "-std=c++17" is already set up by cmake via `CMAKE_CXX_STANDARD`, the other flags I added in addition.

No problem! I think FCC profited a lot from tkLayout so it's nice to contribute something (even if it's just a small patch) :)

**Comment by ghugo83** [comment]
Thanks @vvolkl , I am merging the cleaned CMakeLists now ;)
Cheers

**Pull request merged**
