### PR TITLE
Less overlaps

### PR DESCRIPTION
**Pull request by ghugo83**
+ Possibility of making intersection or union of volumes shapes in tkLayout.
+ 'Truncated cones'.

### CODE REVIEW

**Comment by alkemyst** [comment]
frontEndHybridWidth should only be reduced in those rings where the clash exists and not in the stdinclude

**Comment by ghugo83** [comment]
Yes. I set back frontEndHybridWidth to the standard values.
The modification you mention will be done in another PR, to testing branch.

**Comment by ghugo83** [comment]
Please accept this PR :)

**Comment by alkemyst** [comment]
Closed: will accept the same commits towards dev (PR #121)

**Pull request closed without merging**
