### PR TITLE
OT Cabling map : Lined-up design on (-Z) side

### PR DESCRIPTION
**Pull request by alkemyst**

### CODE REVIEW

**Comment by alkemyst** [comment]
Does not merge simply... will do the opposite

**Comment by ghugo83** [comment]
This allows to have a lined-up Phi-nonants design: the phi sector boundaries are invariant all along Z.

The drawbacks of this design are that it implies a different cabling for disks, dependant whether the disks are placed on (-Z) or (+Z) side.

**Comment by alkemyst** [comment]
Is this an optional function, or the default?

**Comment by ghugo83** [comment]
The default

**Comment by ghugo83** [comment]
Apparently the other design for the (-Z) side was not viable anyway, this is why I made this on 'default'.
Is that fine ?

**Comment by alkemyst** [comment]
Perfectly fine, thanks

**Pull request merged**
